#!/usr/bin/env python3
"""
build-timeline.py — deterministic GSAP timeline generator for Interflow Video Cut.

Turns storyboard.json + public/cards/*.html into the two injected regions of
public/index.html (the copied composition-shell.html):

  <!-- INJECT-CARD-HOSTS -->   → one <div class="card-host clip"> per card
  // INJECT-TIMELINE           → per-card enter / drift / internal-anims / exit

This removes the most repetitive, bug-prone hand-authoring (slip timing,
track-index ordering, finite-repeat drift, data-anim compilation) from the
agent. What it deliberately does NOT do — because they are layout/rhythm
coupled and a wrong guess is a visible defect:

  - video #video-wrap reframes for the DYNAMIC (起伏运镜) rhythm state machine.
    Opt in per card by adding "videoBounds": {left,top,width,height} to a card
    in storyboard.json; the script then emits a reframe tween at that card's
    slip point. Cards without videoBounds leave the video where it was.

What it DOES vary (so the film stops feeling metronomic): each card's entrance
gesture and ambient-drift axis/amplitude are chosen deterministically from
(composition.seed + card index). Same seed → byte-identical output (the
reproducibility contract holds); change composition.seed to reshuffle the whole
film's rhythm. Every gesture lands on the same resting state and touches only
transform + filter (never layout props), so overflow safety is untouched.

Usage:
  python3 build-timeline.py --work "$WORK_DIR" [--slip 0.55]

stdlib only (python3) — no third-party deps.
"""

import argparse
import json
import os
import re
import sys

SLIP_DEFAULT = 0.55
DRIFT_PERIOD = 11  # seconds per ambient-drift leg (legacy default / fallback)

# --- per-card motion variety (deterministic from seed + index) ------------
# Each tuple = (from-vars literal, ease, duration). All gestures land on the
# SAME resting state and animate transform+filter only — never width/height/
# margin — so the overflow contract is unaffected. Picked by (seed + i) so the
# output stays byte-reproducible while cards no longer arrive identically.
ENTER_GESTURES = [
    ("{ opacity: 0, y: 120, filter: 'blur(16px)', scale: 0.94 }", "expo.out", 0.70),   # sink up
    ("{ opacity: 0, y: -110, filter: 'blur(14px)', scale: 0.96 }", "expo.out", 0.70),  # drop down
    ("{ opacity: 0, x: -140, filter: 'blur(14px)', scale: 0.97 }", "power3.out", 0.72),  # slide from left
    ("{ opacity: 0, x: 140, filter: 'blur(14px)', scale: 0.97 }", "power3.out", 0.72),   # slide from right
    ("{ opacity: 0, scale: 0.82, filter: 'blur(18px)' }", "expo.out", 0.75),           # zoom in
    ("{ opacity: 0, y: 70, filter: 'blur(22px)', scale: 0.975 }", "power3.out", 0.80),  # soft focus-pull
]
# Ambient drift variants — (axis, amplitude, period). Kept inside the motion
# guardrail (≤12px translate / ≤0.6° rotate, 9–14s period) so nothing pulses in
# lockstep yet nothing out-moves the speaker.
DRIFT_VARIANTS = [
    ("y", 10, 11),
    ("y", 8, 13),
    ("x", 9, 12),
    ("rotate", 0.5, 12),
    ("y", 12, 9),
]

# --- markers in the shell -------------------------------------------------
HOSTS_MARKER = "<!-- INJECT-CARD-HOSTS -->"
TL_MARKER = "// INJECT-TIMELINE"
HOSTS_BEGIN = "<!-- BEGIN-CARD-HOSTS (generated by build-timeline.py) -->"
HOSTS_END = "<!-- END-CARD-HOSTS -->"
TL_BEGIN = "// BEGIN-TIMELINE (generated by build-timeline.py)"
TL_END = "// END-TIMELINE"


def q(t, fps):
    """Quantize an absolute second to the frame grid, 4 decimals."""
    return round(round(t * fps) / fps, 4)


def fnum(x):
    """Format a number without a trailing .0 when it is integral."""
    if isinstance(x, float) and x.is_integer():
        return str(int(x))
    return str(x)


# --- zone → card-host bounds ---------------------------------------------
def zone_bounds(zone, W, H):
    portrait = H >= W
    if zone == "fullscreen" or zone == "video-overlay":
        return (0, 0, W, H)
    if zone == "lower-third":
        return (0, round(H * 0.70), W, round(H * 0.30))
    if zone == "whiteboard-area":
        if portrait:
            return (0, round(H * 0.55), W, round(H * 0.45))
        return (40, 40, W - 80, H - 80)
    if zone == "side-panel":
        if portrait:
            return (0, round(H * 0.60), W, round(H * 0.40))
        return (round(W * 0.58), 0, round(W * 0.42), H)
    # unknown zone → fullscreen, safest
    return (0, 0, W, H)


# --- data-anim extraction -------------------------------------------------
ANIM_TAG_RE = re.compile(r"<[^>]*\bdata-anim\b[^>]*>", re.IGNORECASE)
# Match attrs in either quote style: name="…" OR name='…' (backref \2 closes it).
ATTR_RE = re.compile(r"""([a-zA-Z0-9\-]+)\s*=\s*(["'])(.*?)\2""")


def extract_anims(card_html):
    """Return a list of dicts, one per element carrying data-anim attributes."""
    out = []
    for tag in ANIM_TAG_RE.findall(card_html):
        attrs = {k.lower(): v for k, _q, v in ATTR_RE.findall(tag)}
        if "data-anim" not in attrs:
            continue
        if "id" not in attrs:
            # without an id we can't target it; skip (the lifecycle still runs)
            continue
        out.append(attrs)
    return out


def compile_anim(card_id, a, fps, comp_dur):
    """Map one element's data-anim attrs to GSAP statement(s). Returns a string."""
    sel = f".card[data-card-id=\"{card_id}\"] #{a['id']}"
    kind = a.get("data-anim", "settle")
    at = float(a.get("data-anim-at", 0.3) or 0.3)
    dur = float(a.get("data-anim-duration", 0.5) or 0.5)
    stag = float(a.get("data-anim-stagger", 0.04) or 0.04)
    # T is absolute = card.startSec + at; caller passes card_start via closure-less arg
    return _emit(kind, sel, at, dur, stag, a, comp_dur)


def _emit(kind, sel, at, dur, stag, a, comp_dur):
    """Return the GSAP statement template with a {T} placeholder for abs time."""
    s = sel.replace("\\", "\\\\")
    if kind == "fade-in":
        return f"tl.fromTo('{s}', {{ opacity: 0 }}, {{ opacity: 1, duration: {dur}, ease: 'expo.out' }}, {{T}});"
    if kind == "fade-out":
        return f"tl.to('{s}', {{ opacity: 0, duration: {dur}, ease: 'power2.in' }}, {{T}});"
    if kind == "slide-in":
        return f"tl.fromTo('{s}', {{ opacity: 0, x: -80 }}, {{ opacity: 1, x: 0, duration: {dur}, ease: 'expo.out' }}, {{T}});"
    if kind == "kinetic-chars":
        return f"tl.from('{s} .char', {{ opacity: 0, y: 8, scale: 0.9, duration: {dur}, ease: 'expo.out', stagger: {stag} }}, {{T}});"
    if kind == "grow-x":
        w = a.get("data-anim-target-w", "420")
        return f"tl.fromTo('{s}', {{ width: 0 }}, {{ width: {w}, duration: {dur}, ease: 'expo.out' }}, {{T}});"
    if kind == "grow-y":
        h = a.get("data-anim-target-h", "120")
        return f"tl.fromTo('{s}', {{ height: 0 }}, {{ height: {h}, duration: {dur}, ease: 'expo.out' }}, {{T}});"
    if kind == "scale-pop":
        return f"tl.fromTo('{s}', {{ opacity: 0, scale: 0.6 }}, {{ opacity: 1, scale: 1, duration: {dur}, ease: 'back.out(1.6)' }}, {{T}});"
    if kind == "mask-reveal":
        return f"tl.fromTo('{s}', {{ clipPath: 'inset(0 100% 0 0)' }}, {{ clipPath: 'inset(0 0 0 0)', duration: {dur}, ease: 'power3.inOut' }}, {{T}});"
    if kind == "count-up":
        frm = a.get("data-anim-from", "0")
        to = a.get("data-anim-to", "100")
        fmt = a.get("data-anim-fmt", "")
        return (f"(function(){{const o={{v:{frm}}};tl.to(o,{{v:{to},duration:{dur},ease:'power2.out',"
                f"onUpdate:function(){{const el=document.querySelector('{s}');if(el)el.textContent=__fmt(o.v,'{fmt}');}}}},{{T}});}})();")
    if kind == "draw-path":
        return (f"(function(){{const el=document.querySelector('{s}');if(!el)return;const L=el.getTotalLength();"
                f"tl.set('{s}',{{strokeDasharray:L,strokeDashoffset:L}},{{T}});"
                f"tl.to('{s}',{{strokeDashoffset:0,duration:{dur},ease:'power2.inOut'}},{{T}});}})();")
    if kind == "drift":
        # ambient loop, no entrance; axis y (default) / x / rotate, amp tiny.
        rep = f"Math.ceil(compDurationSec / {DRIFT_PERIOD})"
        axis = a.get("data-anim-axis", "y")
        amp = a.get("data-anim-amp", "10")
        if axis == "rotate":
            prop = "rotation: '+=0.6'"
        elif axis == "x":
            prop = f"x: '+={amp}'"
        else:
            prop = f"y: '+={amp}'"
        return (f"tl.to('{s}', {{ {prop}, duration: {DRIFT_PERIOD}, ease: 'sine.inOut', "
                f"repeat: {rep}, yoyo: true }}, {{T}});")
    if kind == "parallax-in":
        rep = f"Math.ceil(compDurationSec / {DRIFT_PERIOD})"
        return (f"tl.fromTo('{s}', {{ opacity: 0, y: 40 }}, {{ opacity: 1, y: 0, duration: {dur}, ease: 'expo.out' }}, {{T}}); "
                f"tl.to('{s}', {{ y: '+=8', duration: {DRIFT_PERIOD}, ease: 'sine.inOut', repeat: {rep}, yoyo: true }}, {{T_END}});")
    # 'settle' (default) and anything unknown → the safe settle entrance
    return f"tl.fromTo('{s}', {{ opacity: 0, y: 28, filter: 'blur(6px)' }}, {{ opacity: 1, y: 0, filter: 'blur(0px)', duration: {dur}, ease: 'expo.out' }}, {{T}});"


# --- timing validation ----------------------------------------------------
MIN_ONSCREEN_SEC = 0.6


def _validate_timing(cards, slip):
    """Warn (stderr, non-fatal) on storyboard timing that will render badly.
    The script now owns timeline emission, so it must surface what a human
    hand-authoring would have noticed: too-short cards, non-monotonic starts,
    and the slip-overlap contract (card[i] enters at ~card[i-1].endSec − slip).
    """
    prev_start = None
    prev_end = None
    for i, c in enumerate(cards):
        cid = c.get("id", f"card[{i}]")
        start = float(c["startSec"])
        end = float(c["endSec"])
        if end - start < MIN_ONSCREEN_SEC:
            print(f"build-timeline: WARN {cid} on-screen {end - start:.2f}s < {MIN_ONSCREEN_SEC}s "
                  f"— reads as a flash; merge into a neighbor.", file=sys.stderr)
        if prev_start is not None and start < prev_start:
            print(f"build-timeline: WARN {cid} startSec {start} < previous card's start "
                  f"{prev_start} — cards out of order.", file=sys.stderr)
        if prev_end is not None:
            want = round(prev_end - slip, 2)
            if abs(start - want) > 0.12:
                print(f"build-timeline: WARN {cid} starts at {start} but the silky-slip "
                      f"contract wants ~{want} (prev.endSec − SLIP). Transition may read as a cut/gap.",
                      file=sys.stderr)
        prev_start, prev_end = start, end


# --- generation -----------------------------------------------------------
def gen(work, slip):
    sb_path = os.path.join(work, "storyboard.json")
    idx_path = os.path.join(work, "public", "index.html")
    cards_dir = os.path.join(work, "public", "cards")
    for p in (sb_path, idx_path):
        if not os.path.exists(p):
            sys.exit(f"build-timeline: missing {p}")

    sb = json.load(open(sb_path, encoding="utf-8"))
    comp = sb.get("composition", {})
    fps = comp.get("fps", 30)
    W = comp.get("width", 1920)
    H = comp.get("height", 1080)
    comp_dur = comp.get("durationSeconds", 0)
    seed = int(comp.get("seed", 0) or 0)
    cards = sb.get("cards", [])
    if not cards:
        sys.exit("build-timeline: storyboard has no cards")

    _validate_timing(cards, slip)

    hosts = []
    tl_lines = []
    for i, c in enumerate(cards):
        cid = c["id"]
        start = float(c["startSec"])
        end = float(c["endSec"])
        zone = c.get("zone", "fullscreen")
        track = 2 + i
        x, y, w, h = zone_bounds(zone, W, H)
        ds = q(start, fps)
        dd = q(end - start, fps)

        # --- card-host div, with the card fragment inlined -------------------
        frag_path = os.path.join(cards_dir, f"{cid}.html")
        frag = open(frag_path, encoding="utf-8").read().strip() if os.path.exists(frag_path) else f"<!-- {cid}.html not found -->"
        hosts.append(
            f'<div class="card-host clip" data-card-id="{cid}" '
            f'data-start="{ds:.4f}" data-duration="{dd:.4f}" data-track-index="{track}" '
            f'style="left:{fnum(x)}px;top:{fnum(y)}px;width:{fnum(w)}px;height:{fnum(h)}px;visibility:hidden;opacity:0;">\n'
            f"{frag}\n</div>"
        )

        # --- lifecycle -------------------------------------------------------
        exit_t = q(end - slip, fps)
        tl_lines.append(f"    // ── {cid} [{ds:.4f} … {q(end,fps):.4f}] zone={zone} track={track} ──")
        # optional video reframe at this card's slip point (dynamic rhythm opt-in)
        vb = c.get("videoBounds")
        if vb:
            vclass = c.get("videoClass", "video-wrapper framed")
            tl_lines.append(
                f"    tl.set('#video-wrap', {{ className: '{vclass}' }}, {ds:.4f});")
            tl_lines.append(
                f"    tl.to('#video-wrap', {{ left: {fnum(vb['left'])}, top: {fnum(vb['top'])}, "
                f"width: {fnum(vb['width'])}, height: {fnum(vb['height'])}, duration: 0.7, ease: 'power3.inOut' }}, {ds:.4f});")
        # enter — gesture chosen deterministically from (seed, card index): the
        # film stays byte-reproducible, but adjacent cards no longer arrive the
        # same way (kills the metronome feel). Resting state resets x/y/scale/
        # filter so any gesture lands clean.
        g_from, g_ease, g_dur = ENTER_GESTURES[(seed + i) % len(ENTER_GESTURES)]
        tl_lines.append(
            f"    tl.set('.card-host[data-card-id=\"{cid}\"]', {{ visibility: 'visible' }}, {ds:.4f});")
        tl_lines.append(
            f"    tl.fromTo('.card-host[data-card-id=\"{cid}\"]', "
            f"{g_from}, "
            f"{{ opacity: 1, x: 0, y: 0, filter: 'blur(0px)', scale: 1, duration: {g_dur}, ease: '{g_ease}' }}, {ds:.4f});")
        # ambient drift (finite repeat) — axis/amp/period also rotate per card,
        # inside the ≤12px / ≤0.6° guardrail, so nothing breathes in lockstep.
        d_axis, d_amp, d_period = DRIFT_VARIANTS[(seed + i) % len(DRIFT_VARIANTS)]
        if d_axis == "rotate":
            d_prop = f"rotation: '+={d_amp}'"
        elif d_axis == "x":
            d_prop = f"x: '+={d_amp}'"
        else:
            d_prop = f"y: '+={d_amp}'"
        rep = f"Math.ceil(compDurationSec / {d_period})"
        tl_lines.append(
            f"    tl.to('.card[data-card-id=\"{cid}\"] .root', "
            f"{{ {d_prop}, duration: {d_period}, ease: 'sine.inOut', repeat: {rep}, yoyo: true }}, {ds:.4f});")
        # internal anims (compiled from the card's data-anim attributes)
        for a in extract_anims(frag):
            at = float(a.get("data-anim-at", 0.3) or 0.3)
            dur = float(a.get("data-anim-duration", 0.5) or 0.5)
            kind = a.get("data-anim", "settle")
            t_abs = q(start, fps) if kind == "drift" else q(start + at, fps)
            stmt = compile_anim(cid, a, fps, comp_dur)
            stmt = stmt.replace("{T_END}", f"{q(start + at + dur, fps):.4f}").replace("{T}", f"{t_abs:.4f}")
            tl_lines.append(f"    {stmt}")
        # exit (slip up + blur) then hide
        tl_lines.append(
            f"    tl.to('.card-host[data-card-id=\"{cid}\"]', "
            f"{{ opacity: 0, y: -90, filter: 'blur(10px)', duration: 0.5, ease: 'power2.in' }}, {exit_t:.4f});")
        tl_lines.append(
            f"    tl.set('.card-host[data-card-id=\"{cid}\"]', {{ visibility: 'hidden' }}, {q(end,fps):.4f});")
        tl_lines.append("")

    hosts_block = f"{HOSTS_BEGIN}\n" + "\n".join(hosts) + f"\n  {HOSTS_END}"
    tl_block = f"{TL_BEGIN}\n" + "\n".join(tl_lines) + f"\n    {TL_END}"

    html = open(idx_path, encoding="utf-8").read()
    html = _inject(html, HOSTS_MARKER, HOSTS_BEGIN, HOSTS_END, hosts_block)
    html = _inject(html, TL_MARKER, TL_BEGIN, TL_END, tl_block)
    open(idx_path, "w", encoding="utf-8").write(html)
    print(f"build-timeline: wrote {len(cards)} cards → {idx_path}")


def _inject(html, marker, begin, end, block):
    """Replace a previously-generated region (begin…end) if present, else the marker."""
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pat.search(html):
        return pat.sub(lambda _: block, html)
    if marker in html:
        return html.replace(marker, block, 1)
    sys.exit(f"build-timeline: neither marker '{marker}' nor a prior generated block found in index.html")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", required=True, help="work dir containing storyboard.json + public/")
    ap.add_argument("--slip", type=float, default=SLIP_DEFAULT)
    args = ap.parse_args()
    gen(args.work, args.slip)
